version: "3.8"
services:
  eureka-sv:
    build:
      context: C:\Users\Huawei\Desktop\FullStack\Curso microservicios Spring\City_Tourism\eureka-sv
      dockerfile: Dockerfile
    mem_limit: "512m"
    networks:
        - citytourism-network
    ports:
        - "8761:8761"

  mysql-citytourism:
    image: mysql:latest
    container_name: mysql-citytourism
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}    
      MYSQL_USER: ${DB_USER}      
      MYSQL_PASSWORD: ${DB_PASSWORD}    
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - citytourism-network

  api-gateway:
    build:
        context: C:\Users\Huawei\Desktop\FullStack\Curso microservicios Spring\City_Tourism\api-gateway
        dockerfile: Dockerfile
    mem_limit: "536870912"
    networks:
        - citytourism-network
    ports:
        - "447:447"

    

  cities-service:
    build:
      context: C:\Users\Huawei\Desktop\FullStack\Curso microservicios Spring\City_Tourism\cities-service
      dockerfile: Dockerfile
    depends_on:
      mysql-citytourism:
        condition: service_started
    entrypoint:
      - /bin/sh
      - -c
      - until nc -z mysql-citytourism 3306; do echo 'Waiting for MySQL...'; sleep 3; done; java -jar app_cities.jar
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-citytourism:3306/city_service?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    mem_limit: "536870912"
    networks:
      - citytourism-network
    ports:
      - "8084:8084"

  hotels-service:
    build:
      context: C:\Users\Huawei\Desktop\FullStack\Curso microservicios Spring\City_Tourism\hotels-service
      dockerfile: Dockerfile
    depends_on:
      mysql-citytourism:
        condition: service_started
    entrypoint:
      - /bin/sh
      - -c
      - until nc -z mysql-citytourism 3306; do echo 'Waiting for MySQL...'; sleep 3; done; java -jar app_hotel.jar
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-citytourism:3306/hotel_service?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    mem_limit: "536870912"
    networks:
      - citytourism-network
    ports:
      - "8083:8083"

  restaurant-service:
    build:
      context: C:\Users\Huawei\Desktop\FullStack\Curso microservicios Spring\City_Tourism\restaurant-service
      dockerfile: Dockerfile
    depends_on:
      mysql-citytourism:
        condition: service_started
    entrypoint:
      - /bin/sh
      - -c
      - until nc -z mysql-citytourism 3306; do echo 'Waiting for MySQL...'; sleep 3; done; java -jar app_restaurant.jar
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-citytourism:3306/restaurant_service?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    mem_limit: "536870912"
    networks:
      - citytourism-network
    ports:
      - "8085:8085"

volumes:
  mysql_data:

networks:
  citytourism-network:
    name: city_tourism_citytourism-network
    driver: bridge
